govuk-one-login/di-fec-ga4

- pull_request_template.md
Description
Adds in the pull request template for Github
Tickets
[DFC-27](https://govukverify.atlassian.net/browse/DFC-27)
Steps to Reproduce
N/A
Co-Authored By
N/A
Additional Information
N/A
[DFC-27]: https://govukverify.atlassian.net/browse/DFC-27?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DFC-27] Create PR template

- .babelrc
- .gitignore
- README.md
- index.js
- package-lock.json
- package.json
- src/index.js
- tsconfig.json
- webpack.config.js
Add minify package and relevant script command
(DFC-**)[https://govukverify.atlassian.net/browse/DFC-**]
npm run build
> [DFC-38] Add build command and all dependencies

- .github/workflows/jest.yml
- .github/workflows/prettier.yml
Adds github workflows for:
- Unit tests
- Linting
As pre-merge actions
(DFC-32)[https://govukverify.atlassian.net/browse/DFC-32]
> [DFC-32] - Add github workflow to run tests and linter pre-merge

- package-lock.json
- src/analytics/pageViewTracker/pageViewTracker.ts
- src/utils/utils.spec.ts
- src/utils/validateParameter.ts
Adds a new utils function `validateEventData` plus related unit tests
eventData is defined as `Object` due to type errors being thrown when testing the `false` test case
https://govukverify.atlassian.net/browse/DFC-66
> [DFC-66] Validate data from args

- package.json
- src/analytics/navigationTracker/navigationTracker.test.ts
- src/analytics/navigationTracker/navigationTracker.ts
Bump correctly the version.
(DFC-**)[https://govukverify.atlassian.net/browse/DFC-**]
> Bump version + improvement on navigation tracker

- PACKAGE-README.md
- src/analytics/core/core.test.ts
- src/analytics/core/core.ts
- src/analytics/formTracker/formTracker.test.ts
- src/analytics/navigationTracker/navigationTracker.test.ts
- src/analytics/navigationTracker/navigationTracker.ts
- src/analytics/pageViewTracker/pageViewTracker.test.ts
- src/analytics/pageViewTracker/pageViewTracker.ts
- src/cookie/cookie.test.ts
- src/cookie/cookie.ts
- Implementation of the cookie consent logic (DFC-123)
- fix bug DFC-131
- add documentation (DFC-133)
(DFC-123)[https://govukverify.atlassian.net/browse/DFC-123]
(DFC-131)[https://govukverify.atlassian.net/browse/DFC-131]
(DFC-133)[https://govukverify.atlassian.net/browse/DFC-133]
> DFC-123 add cookie management (+DFC-131)

- PACKAGE-README.md
- src/analytics/baseTracker/baseTracker.test.ts
- src/analytics/pageViewTracker/pageViewTracker.interface.ts
- src/analytics/pageViewTracker/pageViewTracker.test.ts
- src/analytics/pageViewTracker/pageViewTracker.ts
add 6 new parameters and add new unit tests
(DFC-142)[https://govukverify.atlassian.net/browse/DFC-142]
> DFC-142: PageViewTracker / add 6 new parameters and add new unit tests

- PACKAGE-README.md
- src/analytics/baseTracker/baseTracker.ts
- src/analytics/core/core.test.ts
- src/analytics/core/core.ts
- src/analytics/formChangeTracker/formChangeTracker.ts
- src/analytics/formErrorTracker/formErrorTracker.test.ts
- src/analytics/formErrorTracker/formErrorTracker.ts
- src/analytics/formResponseTracker/formResponseTracker.test.ts
- src/analytics/formResponseTracker/formResponseTracker.ts
- src/analytics/formTracker/formTracker.test.ts
- src/analytics/formTracker/formTracker.ts
- src/analytics/pageViewTracker/pageViewTracker.test.ts
- src/analytics/pageViewTracker/pageViewTracker.ts
- Add Form Error Tracker
- Refactor Form Trackers architecture
(DFC-94)[https://govukverify.atlassian.net/browse/DFC-94]
(DFC-96)[https://govukverify.atlassian.net/browse/DFC-96]
(DFC-99)[https://govukverify.atlassian.net/browse/DFC-99]
> DFC-94: add form error tracker + form trackers refactoring

- src/analytics/baseTracker/baseTracker.test.ts
- src/analytics/baseTracker/baseTracker.ts
- src/analytics/navigationTracker/navigationTracker.interface.ts
- src/analytics/navigationTracker/navigationTracker.ts
- add new properties into navigation tracker
- add common functions into base tracker
(DFC-161)[https://govukverify.atlassian.net/browse/DFC-161]
> DFC-161: add new properties into navigation tracker

- package-lock.json
- package.json
- src/utils/pii-remover.ts
- src/utils/utils.spec.ts
- src/utils/validateParameter.ts
- Add pii remover script
(DFC-169)[https://govukverify.atlassian.net/browse/DFC-169]
> DFC-169: add pii remover script

- package.json
- src/utils/pii-remover.ts
- src/utils/utils.spec.ts
(DFC-194)[https://govukverify.atlassian.net/browse/DFC-194]
> DFC-194: add neww pii remover date format

- PACKAGE-README.md
(DFC-203)[https://govukverify.atlassian.net/browse/DFC-203]
> dfc-203:modify package readme

- package-lock.json
- package.json
- webpack.config.js
Description:
Disable blocking eslint rules for the build file.
Changes:
- modify webpack config and add comment at the beginning of the build file.
> DFC-307: disable eslint rules in the build file

- package.json
- src/analytics/baseTracker/baseTracker.test.ts
- src/analytics/baseTracker/baseTracker.ts
Organisations and primary_publishing_organisation constants were wrong.
I updated its.
> DFC-370: Update constants in baseTracker

- package-lock.json
- src/analytics/baseTracker/baseTracker.ts
- src/analytics/core/core.interface.ts
- src/analytics/formErrorTracker/formErrorTracker.ts
- src/analytics/formResponseTracker/formResponseTracker.ts
- src/analytics/formTracker/formTracker.interface.ts
- src/analytics/formTracker/formTracker.test.ts
- src/analytics/formTracker/formTracker.ts
- src/analytics/navigationTracker/navigationTracker.ts
- src/cookie/cookie.ts
- src/utils/pii-remover.ts
- Refactored the [getFormFields](https://sonarcloud.io/project/issues?open=AYzzz_Dk1aQAjXW20mlE&id=govuk-one-login_di-fec-ga4) function to try and reduce its cognitive complexity from 27 points.
- Replaced additional checks in if statements with [optional chain expressions](https://sonarcloud.io/project/issues?open=AY1U4q8-7l6Lxduq0dLH&id=govuk-one-login_di-fec-ga4) for improved readability.
- Transitioned the for loop in the cookie hiding button logic to utilise a [for-of loop](https://sonarcloud.io/project/issues?open=AYx9OYGPzDN-BIKbnAfu&id=govuk-one-login_di-fec-ga4).
- Renamed formTrackerOptionsInterface to adhere to [Pascal case](https://sonarcloud.io/project/issues?open=AYx9OYDgzDN-BIKbnAfK&id=govuk-one-login_di-fec-ga4), aligning with TypeScript interface naming conventions.
- …
> DFC-365 | SonarCloud: Code Smells

- docs/analytics.md
- docs/formTrackers.md
- docs/navigationTracker.md
- docs/pageViewTracker.md
- package.json
- src/analytics/formChangeTracker/formChangeTracker.ts
> DFC-392 add docs and remove console log

- src/analytics/core/core.interface.ts
- src/analytics/core/core.ts
- src/analytics/formResponseTracker/formResponseTracker.test.ts
- src/analytics/formResponseTracker/formResponseTracker.ts
- src/analytics/formTracker/formTracker.interface.ts
- remove disableFreeTextTracking option
- remove disableAnalyticsCookie  option
https://govukverify.atlassian.net/browse/DFC-433
Out of scope:
- Update the readme --> Already done into https://github.com/govuk-one-login/di-fec-ga4/pull/53
> DFC-433: remove disableFreeTextTracking and disableAnalyticsCookie options

- PACKAGE-README.md
- add uacontainerid
- remove useless options
- add paragraph about cookie functions.
https://govukverify.atlassian.net/browse/DFC-432
https://govukverify.atlassian.net/browse/DFC-436
> DFC-432 / DFC-436: update package readme with missing information

- src/analytics/formErrorTracker/formErrorTracker.test.ts
- src/analytics/formErrorTracker/formErrorTracker.ts
- src/analytics/formResponseTracker/formResponseTracker.test.ts
- src/analytics/formTracker/formTracker.test.ts
- src/analytics/formTracker/formTracker.ts
https://govukverify.atlassian.net/browse/DFC-449
> DFC-449: Add type password into form trackers

- src/analytics/formResponseTracker/formResponseTracker.test.ts
- src/analytics/formResponseTracker/formResponseTracker.ts
- src/analytics/formTracker/formTracker.test.ts
- src/analytics/formTracker/formTracker.ts
Form Response event needs to be cancelled if form is not valid.
> DFC-447: check if form is valid before to send form response event

- jest.config.js
- src/analytics/navigationTracker/navigationTracker.test.ts
- src/analytics/pageViewTracker/pageViewTracker.test.ts
https://govukverify.atlassian.net/browse/DFC-502
> DFC-502: Jest / Config improvement + unit test fixes

- src/analytics/formChangeTracker/formChangeTracker.test.ts
- src/analytics/formChangeTracker/formChangeTracker.ts
- src/analytics/formErrorTracker/formErrorTracker.test.ts
- src/analytics/formErrorTracker/formErrorTracker.ts
- src/analytics/formResponseTracker/formResponseTracker.test.ts
- src/analytics/formResponseTracker/formResponseTracker.ts
- src/analytics/formTracker/formTracker.test.ts
- src/analytics/formTracker/formTracker.ts
- Get form which is contained into main content container
- Apply to form trackers: form error, form change and form response.
> DFC-507: improve get form element in form trackers

- package.json
- src/analytics/navigationTracker/navigationTracker.ts
https://govukverify.atlassian.net/browse/DFC-508
> DFC-508: Exclude error links from navigation tracker

- package-lock.json
- package.json
Required as the build command did not complete correctly
> chore/release version 1.0.1

- package-lock.json
- package.json
> chore/release version 1.0.2

- PACKAGE-README.md
- package-lock.json
- package.json
- src/components/ga4-opl/macro.njk
- src/components/ga4-opl/template.njk
- webpack.config.js
Changes:
- Add OPL nunjuck component.
- Update webpack config.
- Update the package readme.
> DFC-491: Add OPL component into the package

- src/analytics/formTracker/formTracker.test.ts
- src/analytics/formTracker/formTracker.ts
- Manage 2 new scenarios for date fields:
--> multiple of date fields form
--> date field in a multiple fields form
> DFC-457: Improve date field management

- .gitignore
- pull_request_template.md
Chore task to add PR template to this repository to improve consistency
[x] - Are the commit messages for this PR in line with the GDS way?
> Chore: Add PR Template

- src/analytics/baseTracker/baseTracker.ts
- src/analytics/formErrorTracker/formErrorTracker.ts
- src/analytics/formResponseTracker/formResponseTracker.ts
Small PR to remove console.log's from the GA4 implementation
[(DFC-**)[https://govukverify.atlassian.net/browse/DFC-**]](https://govukverify.atlassian.net/browse/DFC-451)
- run `npm build`
- Copy contents from dist/analytics, paste contents in a chosen target repository's node_modules
- Open google tag manage
- When initialising trackers, no console.log's appear
> Remove console.logs

- src/analytics/formTracker/formTracker.ts
- src/analytics/navigationTracker/navigationTracker.ts
- tsconfig.json
SonarCloud analysis has identified several issues (21) in the codebase that need to be addressed to improve code quality, maintainability, and security. This PR addresses/ resolves some of the issues deemed relevant from the SonarCloud report.
Issues can be found [here](https://sonarcloud.io/project/issues?resolved=false&id=govuk-one-login_di-fec-ga4)
You can find the link to the Google Doc containing the review of identified issues, including explanations on what has been resolved and why, as well as noting that some issues do not require resolution as they were found not to be genuine issues after investigation. Click [here](https://docs.google.com/document/d/11hr55y03Cg0ZNkr6kT5fNtBh7zK-o5sWpc4a0dYd3zo/edit)
(DFC-610)[https://govukverify.atlassian.net/browse/DFC-610]
[ ] - Are the …
> DFC-610 | Resolve SonarCloud Issues

- package-lock.json
- pull_request_template.md
> Chore: Fix typo in PR template

- .eslintrc.json
- package-lock.json
- package.json
- src/analytics/baseTracker/baseTracker.test.ts
- src/analytics/baseTracker/baseTracker.ts
- src/analytics/core/core.test.ts
- src/analytics/core/core.ts
- src/analytics/formChangeTracker/formChangeTracker.test.ts
- src/analytics/formChangeTracker/formChangeTracker.ts
- src/analytics/formErrorTracker/formErrorTracker.test.ts
- src/analytics/formErrorTracker/formErrorTracker.ts
- src/analytics/formResponseTracker/formResponseTracker.test.ts
- src/analytics/formResponseTracker/formResponseTracker.ts
- src/analytics/formTracker/formTracker.test.ts
- src/analytics/formTracker/formTracker.ts
- src/analytics/navigationTracker/navigationTracker.test.ts
- src/analytics/navigationTracker/navigationTracker.ts
- src/analytics/pageViewTracker/pageViewTracker.test.ts
- src/analytics/pageViewTracker/pageViewTracker.ts
- src/analytics/selectContentTracker/selectContentTracker.test.ts
- src/analytics/selectContentTracker/selectContentTracker.ts
- src/cookie/cookie.test.ts
- src/cookie/cookie.ts
- src/index.ts
- src/utils/applyDefaults.ts
- src/utils/pii-remover.ts
- src/utils/validateParameter.ts
- webpack.config.js
This enables eslint for the project and fixes the errors it's flagging.
Additional rules have been added to try and keep some consistency with how the codebase is already formatted.
[DFC-\*\*](https://govukverify.atlassian.net/browse/DFC-**)
[ ] - Are the commit messages for this PR in line with the GDS way?
[ ] - Have the changes in this PR been tested locally (if required)
[ ] - Have additional tests been added where required?
[ ] - Does the feature pass accessibility checks? (UI Components only)
> fix: enable eslint

- package-lock.json
- package.json
Patch release due to inconsistent files present in 3.0.0
* Bump ws from 8.14.2 to 8.17.1 by @dependabot in https://github.com/govuk-one-login/di-fec-ga4/pull/81
* fix: enable eslint by @nickhealGDS in https://github.com/govuk-one-login/di-fec-ga4/pull/90
* [DFC-646] - Add Core specific header classes to enable navigation by @di-aholme in https://github.com/govuk-one-login/di-fec-ga4/pull/95
**Full Changelog**: https://github.com/govuk-one-login/di-fec-ga4/compare/v3.0.0...v3.0.1
[DFC-646]: https://govukverify.atlassian.net/browse/DFC-646?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Release/version 3.0.1
