govuk-one-login/di-fec-ga4

jest.config.js, package-lock.json, package.json, src/analytics/pageViewTracker/pageView.test.ts, src/analytics/pageViewTracker/pageViewInterface.ts, src/analytics/pageViewTracker/pageViewTracker.ts
Adds Jest testing framework to the project with relevant script configuration and an initial unit test
(DFC-32)[https://govukverify.atlassian.net/browse/DFC-32]
Pull code locally
Execute unit test command `npm run test`
=> [DFC-32] Add jest testing framework, plus initial unit test

PACKAGE-README.md, package.json, src/analytics/baseTracker/baseTracker.ts, src/analytics/core/core.ts, src/analytics/navigationTracker/navigationTracker.interface.ts, src/analytics/navigationTracker/navigationTracker.test.ts, src/analytics/navigationTracker/navigationTracker.ts, src/analytics/navigationViewTracker/navigationViewTracker.ts, src/analytics/pageViewTracker/pageViewTracker.test.ts, src/analytics/pageViewTracker/pageViewTracker.ts, src/utils/utils.spec.ts, src/utils/validateParameter.ts
- Add a new Navigation tracker based on GA4 implementation guide
(DFC-85)[https://govukverify.atlassian.net/browse/DFC-85]
(DFC-92)[https://govukverify.atlassian.net/browse/DFC-92]
=> DFC-85/DFC-92: add navigation tracker

src/analytics/baseTracker/baseTracker.test.ts, src/analytics/baseTracker/baseTracker.ts, src/analytics/core/core.ts, src/analytics/formTracker/formTracker.interface.ts, src/analytics/formTracker/formTracker.test.ts, src/analytics/formTracker/formTracker.ts, src/utils/utils.spec.ts, src/utils/validateParameter.ts
Add the Form Response Tracker:
- Add listener on form submit
- Manage all fields type values
(DFC-80)[https://govukverify.atlassian.net/browse/DFC-80]
(DFC-81)[https://govukverify.atlassian.net/browse/DFC-81]
=> DFC-80/DFC-81: add form response tracker

src/analytics/navigationTracker/navigationTracker.test.ts, src/analytics/navigationTracker/navigationTracker.ts
- Click on header logo or footer logo is now tracked also.
- Improve how we detect footer link or header link
(DFC-128)[https://govukverify.atlassian.net/browse/DFC-128]
(DFC-130)[https://govukverify.atlassian.net/browse/DFC-130]
=> DFC-128/DFC-130: track click on logo icon

src/analytics/navigationTracker/navigationTracker.test.ts, src/analytics/navigationTracker/navigationTracker.ts
This PR updates the logic which searches for 'button' elements, and replaces this lookup with class names
(DFC-143)[https://govukverify.atlassian.net/browse/DFC-143]
GA4 Demo app
`npm run dev` this means you will not need to restart the server everytime there is a change when testing the ga4 tracker changes
GA4 app
Run `npm build` this will build the latest code in the analytics.js file then…
run `cp dist/lib/analytics.js ../di-fec-ga4-demo/node_modules/one-login-ga4/lib` this will copy the bundled file to the GA4 Demo app as a ‘mock’ type file, and overwrite the node modules version from the NPM registry - this command will only work if you have your repos in the same directory, otherwise replace the with your relative path
When you select any 'govuk-button' this will come through on the …
=> Amend generic button logic and tests

src/analytics/formErrorTracker/formErrorTracker.test.ts, src/analytics/formErrorTracker/formErrorTracker.ts
Inconsistent Types in Data Layer.
All form trackers need to get the field type from the same function.
(DFC-158)[https://govukverify.atlassian.net/browse/DFC-158]
=> DFC-158: fix inconsistent types into form error tracker

src/analytics/navigationTracker/navigationTracker.test.ts, src/analytics/navigationTracker/navigationTracker.ts
Description
Adds logic to set the phase banner links on navigation change
Tickets
(DFC-129)[https://govukverify.atlassian.net/browse/DFC-129]
Steps to Reproduce
Click on the phase banner links
Validate this on local + gtm
Added header, footer and phase banner check as the tests were failing without them
=> Add functionality to set phase banner

src/analytics/formChangeTracker/formChangeTracker.test.ts, src/analytics/formChangeTracker/formChangeTracker.ts
Further updates to values need to be made. In accordance to [documentation](https://govukverify.atlassian.net/wiki/spaces/PI/pages/3603791886/WIP+GA4+Implementation+Guide#Form-Change-Response-IN-SCOPE) , the action parameter value should be “change response”  and text should be “change” to reflect text of link.
(DFC-165)[https://govukverify.atlassian.net/browse/DFC-165]
=> DFC-165: fix form change tracker values error

src/analytics/formErrorTracker/formErrorTracker.test.ts, src/analytics/formResponseTracker/formResponseTracker.test.ts, src/analytics/formTracker/formTracker.test.ts, src/analytics/formTracker/formTracker.ts
In the form trackers, radio form is identify with the type “radio“ instead of “radio buttons“.
(DFC-164)[https://govukverify.atlassian.net/browse/DFC-164]
=> DFC-164: fix radio type error

src/analytics/navigationTracker/navigationTracker.test.ts, src/analytics/navigationTracker/navigationTracker.ts
(DFC-159)[https://govukverify.atlassian.net/browse/DFC-159]
Adds the section property based on the link section the a link parent element
The only element which is hard to test is the tag 'nav' which out outs 'menu-links' according to the documentation link here (number 2)
Note: this is not header links which is part of the header component
The only example I can find on the design system is on the GOV design system site, which uses the 'nav' tag 
https://design-system.service.gov.uk/components/
=> Dfc 159 manage the section property

src/analytics/formResponseTracker/formResponseTracker.test.ts, src/analytics/formResponseTracker/formResponseTracker.ts, src/analytics/formTracker/formTracker.test.ts, src/analytics/formTracker/formTracker.ts
1. **Iterative Event Generation:** Updated the trackFormResponse method to iterate through the array of FormField objects, generating events for each field individually rather than a singular event for the whole form 
2.  **New Utility Function - getSectionValue:**
Created a new utility function, getSectionValue, which the FormResponseTracker uses to retrieve the section value associated with each field.
- Section Value Determination:
Implemented checks in getSectionValue to determine the appropriate section value for each field.
If the field is within a` <fieldset>`, it retrieves the` <legend>` using a query selector and stores it in a string. This is targeted at radio and checkbox fields.
If the field has an associated label, it retrieves and stores the label in a string. This is …
=> DFC-186| Update response tracker to be able to manage multiple fields

src/analytics/formErrorTracker/formErrorTracker.test.ts, src/analytics/formErrorTracker/formErrorTracker.ts, src/analytics/formResponseTracker/formResponseTracker.ts
Changes Made:
1. **trackFormError Update:**
- Iterated through fields in the form group.
- Pushed an event_data object for each field with an error message.
2. **getErrorFields Function Added:**
- Retrieves fields with only error messages.
- Ensures trackFormResponse only pushes event_data objects for fields with errors.
3. **Unit Tests Added:**
- Added tests for the new getErrorFields function.
4. **getErrorMessage Update:**
- Retrieves error message associated with a specific field.id.
- Ensures the correct error message is sent to DL.
5. **Unit Tests Added:**
- Tests for getErrorMessage to verify correct error message retrieval.
- Tests for the updated FormErrorTracker to handle multiple fields with error messages.
6. **Refactoring:**
- Removed getType function and its associated unit …
=> DFC-187 | Update error tracker to manage multiple fields

src/analytics/navigationTracker/navigationTracker.test.ts, src/analytics/navigationTracker/navigationTracker.ts
Changed all instances of "license" to "licence" for NavigationTracker
=> DFC-291 | BUG | Navigation Tracker returns "license" as section value for licence link in footer

package.json, src/analytics/core/core.ts
accept analytics tracking doesn't load correctly the gtm script
(DFC-296)[https://govukverify.atlassian.net/browse/DFC-296]
User accepts analytics cooking tracking.
Result: GTM script is loaded without the gtmId
=> DFC-296: fix loadgtmscript bug

PACKAGE-README.md, src/analytics/formTracker/formTracker.test.ts, src/analytics/formTracker/formTracker.ts
Upon GA4 implementation on the Lime Pod's repos , it was discovered that due to the non-standard approach of implementing radio and checkbox forms, the formResponse and formError trackers were unable to retrieve the correct section values. Therefore updates to the getSectionValue function to expand its scope, so that : 
If a checkbox or radio form does not have a legend, the getSectionValue will look for a :
- `<h1> </h1>`  or `<h2> </h2>`with a rel attribute OR
- first` <h1> </h1>` on the page OR
- first `<h2> </h2>` on the page 
- Added the unit test for updated function
- updated package README with steps for implementation
In the ipv-cri-dl-front repo , they have a checkbox with no legend and have used a `<h2> </h2> ` as the tag to hold their section title, so I added a REL attribute …
=> DFC - 297 | BUG | Form Response & Error Tracker | getSectionValue Function

package.json
Use npm ci to install dependencies in pipelines to ensure complete consistency between validation and build of packages. As a bonus it should also be a tiny bit faster.
=> DFC-196: add npm ci in the build command

PACKAGE-README.md, package-lock.json, src/analytics/core/core.interface.ts, src/analytics/core/core.ts, src/cookie/cookie.test.ts, src/cookie/cookie.ts
Modifies the setCookie functionality to take a value specified in the Options object set in the consuming repository. If no value is provided, it will default to `account.gov.uk`. This will enable the cookie to persist throughout the journey.
The nature of this change makes it difficult to test. Localhost will not allow cookies to be set to alternative domains and the domain of a cookie is not retrievable to assert the value in a unit test.
https://govukverify.atlassian.net/browse/DFC-372 - TD ticket for unit tests
(DFC-371)[https://govukverify.atlassian.net/browse/DFC-371]
=> [DFC-371] - Review and update cookie domain registration for package

package.json, src/analytics/pageViewTracker/pageViewTracker.ts, src/cookie/cookie.ts
Now, other trackers are able to know if visitor has cookie set in the browser.
=> DFC-368: improve cookie state management

src/cookie/cookie.test.ts, src/cookie/cookie.ts, src/utils/validateParameter.ts
Following discussion with (Boris Frontend Developer | SSE), inline style change creates a security issue. And some frontend repos don’t allow it.
So we need to change its:
add this instead: "govuk-!-display-none" when we want to hide it
remove  "govuk-!-display-none" (if needed) and add another govuk display class when we want to show.
=> DFC-431: add and remove class instead to change inline style

src/analytics/navigationTracker/navigationTracker.ts
Navigation tracker url param limit needs to be 500
=> DFC-456: change url param limit

src/analytics/pageViewTracker/pageViewTracker.test.ts, src/analytics/pageViewTracker/pageViewTracker.ts
getLoggedInStatus needs to return one of the 3 values: logged in, logged out, or undefined
=> DFC-414: getLoggedInStatus - add "undefined" condition

src/analytics/formResponseTracker/formResponseTracker.ts, src/analytics/formTracker/formTracker.test.ts, src/analytics/formTracker/formTracker.ts
Date fields are compose of 3 fields: day month year.
Data and analytics team wants us to create only 1 event instead of 1 event per field.
=> DFC-444: Manage date fields and combine them into 1 event

src/analytics/navigationTracker/navigationTracker.test.ts, src/analytics/navigationTracker/navigationTracker.ts
Following Sam Evatt's comment (see jira ticket https://govukverify.atlassian.net/browse/DFC-509), I added an internal url which set the value of external to false.
=> DFC-509: Add internal url into navigation tracker

PACKAGE-README.md, package-lock.json, package.json
Renames the `@govuk-one-login/one-login-analytics` package to `@govuk-one-login/frontend-analytics` in compliance with naming requirements
Release v1.0.3
https://govukverify.atlassian.net/browse/DFC-550
=> [DFC-550] - Rename one-login-analytics to frontend-analytics

src/analytics/navigationTracker/navigationTracker.test.ts, src/analytics/navigationTracker/navigationTracker.ts
Refactor the `isHeaderMenuBarLink` function to check if the element is contained within the first header or nav element. QA testing on the Home GA4 implementation highlighted an issue with tracking submenu items, where the parameter type is showing `generic link` instead of `header menu bar`. Currently, the function we use to determine if it is a HeaderMenuBar only checks the first header tag on the page, which is insufficient. As they already have a header element on the page, I have added a check for the first nav tag on the page. In the Home repo and Demo app, submenu links are located within nav tags.
(DAC-3541)[https://govukverify.atlassian.net/browse/DAC-3541]
1. Run `npm run build`.
2. Copy the contents of the analytics.js file
3. Navigate to the [di-account-management-frontend …
=> DAC-3541 | Refactor isHeaderMenuBarLink function 

package-lock.json, package.json, src/analytics/baseTracker/baseTracker.ts, src/analytics/core/core.ts, src/analytics/pageViewTracker/pageViewTracker.interface.ts
As a result of building the GA solution as an extension of existing functionality, some required initialisation events were missed and not discovered due to UA running in parallel during the QA process.
New events are now fired when the Analytics package is initialised as part of core functionality, allowing us to confirm events coming from the google tag
[DFC-\*\*](https://govukverify.atlassian.net/browse/DFC-**)
- Disable UA in test repository
- Build analytics dist folder
- Copy output of second command into the node_modules folder of the target repository, replacing the existing analytics.js file
- Build frontend as normal, open localhost via tag assistant
- Cause some GA events to fire, then in the tag assistant check the `G-MHX9DPZ660` tag for 'Hits'
- The same events in the …
=> UA Fix: Add missing events to initialise the Google Tag

package.json, src/analytics/baseTracker/baseTracker.test.ts, src/analytics/baseTracker/baseTracker.ts, src/analytics/core/core.ts, src/analytics/formChangeTracker/formChangeTracker.test.ts, src/analytics/formChangeTracker/formChangeTracker.ts, src/analytics/navigationTracker/navigationTracker.test.ts, src/analytics/navigationTracker/navigationTracker.ts, src/analytics/pageViewTracker/pageViewTracker.test.ts, src/analytics/pageViewTracker/pageViewTracker.ts
The data team requested that the **formChangeTracker** be triggered when a user clicks on a link, rather than on the page where the user changes the details. Additionally, the **navigationTracker** was incorrectly firing when the user clicks on a change link. This PR addresses both issues.
##What was done
Remove old trigger from pageViewTracker which triggered formChangeTracker when there was edit=true in url.
Updated the FormChange Tracker to:
1.  Initialise EventListener: Added an EventListener to formChangeTracker which detect user clicks on "Change" links, triggering the tracker.
2. Create **isChangeLink** Function: Introduced the isChangeLink function to the baseTracker to be utilised by both the **formChangeTracker** and **navigationTracker**. This function examines the query …
=> DAC-3613 - Update trigger and tests for formChangeTracker

package-lock.json, package.json, src/analytics/pageViewTracker/pageViewTracker.test.ts, src/analytics/pageViewTracker/pageViewTracker.ts
Adds the ability to persist taxonomy level 2 values dynamically between pages. This is functionality which will only be used in Auth, but adding the functionality to the GA4 package was a cleaner and simpler solution than directly adding this to the auth frontend
[DFC-319](https://govukverify.atlassian.net/browse/DFC-319)
- Install package into a target repository
- Modify one of the page view trackers to change the taxonomy level 2 value to `persisted from previous page`
- Test the UI, the string from step 2 should be replaced with the previous pages taxonomy level 2 value in the DLP
[x] - Are the commit messages for this PR in line with the GDS way?
[x] - Have the changes in this PR been tested locally (if required)
[x] - Have additional tests been added where required?
[DFC-319]: …
=> DFC-319 - Add persisting taxonomy values to GA4 package

PACKAGE-README.md, docs/analytics.md, src/analytics/core/core.interface.ts, src/analytics/core/core.test.ts, src/analytics/core/core.ts, src/analytics/pageViewTracker/pageViewTracker.test.ts, src/analytics/pageViewTracker/pageViewTracker.ts, src/index.ts
The initial implementation of this package had the feature flag naming as `disabled` which has been a frequent piece of feedback from the pods and does not conform with the GDS way. This work renames those flags and mirrors the feature flag logic so that the pods can rename their environment variables to use `enabled` and avoid confusion
[DFC-629](https://govukverify.atlassian.net/browse/DFC-629)
- Built the package
- Place the analytics.js file in the local instance of any repo
NOTE: If you use a CRI for this, remember the additional common-express steps
- Update the feature flag references in the consuming repo
- Test in the tag manager, expected behaviour is:
GA4 Flag set to `true`: GA4 is enabled
GA4 Flag set to `false`: GA4 is disabled
GA4 Flag not provided: GA4 is disabled
There …
=> [DFC-629] - Rename feature flags to positive

.github/workflows/prettier.yml, src/analytics/navigationTracker/navigationTracker.test.ts, src/analytics/navigationTracker/navigationTracker.ts, tsconfig.json
`ipv-core-front` uses a unique Header component with different classes than the generic GOVUK component. As a result, the navigation tracker does not fire in this case so the array of hooks has been extended to accommodate this.
[DFC-646](https://govukverify.atlassian.net/browse/DFC-646)
[x] - Are the commit messages for this PR in line with the GDS way?
[x] - Have the changes in this PR been tested locally (if required)
[x] - Have additional tests been added where required?
[DFC-646]: https://govukverify.atlassian.net/browse/DFC-646?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DFC-646] - Add Core specific header classes to enable navigation

src/analytics/navigationTracker/navigationTracker.test.ts, src/analytics/navigationTracker/navigationTracker.ts
Modifies the `isExternal` check to assert whether or not `account.gov.uk` is present in the URL.
[DFC-643](https://govukverify.atlassian.net/browse/DFC-643)
[x] - Are the commit messages for this PR in line with the GDS way?
[x] - Have additional tests been added where required?
[DFC-643]: https://govukverify.atlassian.net/browse/DFC-643?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DFC-643 - Modify isExternal Check to cover all environments

package.json
Minor configuration update to remove the `files` array from `package.json`. This option limited the files that would be picked up by `npm publish`, preventing the `componentsd/ga4-opl` folder from being included.
The command `npm run pub --dry-run true` will output in the terminal the structure of the release. With `"files": ["lib/"]` included, only `lib/`, `package.json` and `README.md` are included in the release
With
Without
=> Chore: Remove files config from package.json

CODEOWNERS
This adds a CODEOWNERS file marking the team `@govuk-one-login/digital-identity-frontend-capability` as codeowners for this repository
[DFC-670](https://govukverify.atlassian.net/browse/DFC-670)
[DFC-670]: https://govukverify.atlassian.net/browse/DFC-670?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DFC-670] - Add CODEOWNERS File
